### ISSUE TITLE
Question: How to add URLs in Command Line on macOS? (the input device is not a TTY error)

### ISSUE THREAD

**Issue by VanillaChief** [ArchiveBox/ArchiveBox#1042]
I have archivebox running on my Mac with docker-compose. Everything is working so far, I can add URLs via the web GUI.

But when I try for example to ingest a textfile with URLs via the commandline, I always get "the input device is not a TTY".

The documentation is a bit sparse on that point, as it just says: "pass in URLs via stdin." I don't really understand what is meant by that. When I copy `docker-compose run archivebox add < ~/Downloads/bookmarks.html` (and change the path of course) I always get "the input device is not a TTY"

What do I need to do to be able to ingest URLs in the command line?

**Comment by pirate** [comment]
Please post your `docker-compose.yml` file and the output of `docker-compose run archivebox version`.

**Comment by pirate** [comment]
Closing as stale.

**Comment by dohlin** [comment]
@pirate Is there any chance you can explain what this error means?  I too am getting this error, although it's on a fresh install of Ubuntu 24.04, v0.7.2.  I thought everything was working, but passing in my Firefox .json export it doesn't like:

![image](https://github.com/user-attachments/assets/d838f484-b607-4e74-965b-4b8db7ebd146)

Here is my docker compose run archivebox version info:

![image](https://github.com/user-attachments/assets/98a8e3d6-6c18-4dc5-9ccd-f5a105e7615a)

On my old server, I used "docker-compose" and it did work...but "docker compose" doesn't seem to want to play ball.  I will admit, I get pretty confused as the doc seems to flop back and forth between "docker compose" and "docker-compose" which from the tiny bit of reading I've done 'docker compose' seems like it's the newer/better option nowadays, so that's all I've installed on this new server I'm trying to spin up (if I try to run "docker-compose" I get the normal message telling me it's not installed).  Do I absolutely need to install this alongside docker-compose and memorize which commands need the dash vs which ones don't?  Or is there a way to make "docker compose" work for this task?  Sorry if I'm missing something obvious here.

**Comment by pirate** [comment]
`docker-compose` used to be a separate package but they merged it into docker, so as of ~2022 you should only run `docker compose`

As for the -T / -it stuff I agree it is a confusing common issue for new docker users. Basically the only thing to remember is:

- `docker run ...` sometimes needs `-it`
- `docker compose run ...` sometimes needs `-T`

(Never the other way around)

Basically the flags tell the docker daemon whether to expect interactive input on stdin, a pipe, or something else, and the default is different between plain docker and compose, hence the different args to change the default. 

Hope that helps!

**Comment by dohlin** [comment]
> `docker-compose` used to be a separate package but they merged it into docker, so as of ~2022 you should only run `docker compose`
> 
> As for the -T / -it stuff I agree it is a confusing common issue for new docker users. Basically the only thing to remember is:
> 
>     * `docker run ...` sometimes needs `-it`
> 
>     * `docker compose run ...` sometimes needs `-T`
> 
> 
> (Never the other way around)
> 
> Basically the flags tell the docker daemon whether to expect interactive input on stdin, a pipe, or something else, and the default is different between plain docker and compose, hence the different args to change the default.
> 
> Hope that helps!

Appreciate the crash course, definitely helps out!!
