### ISSUE TITLE
Add user problem 

### ISSUE THREAD

**Issue by frizerabg** [ArchiveBox/ArchiveBox#1166]
Kudos for the job well done! It's great!
But I have the following problem: the app runs on a Synology DSM 7.2 NAS without a problem until I try to create another user other than supreuser so that his and my site archives can't be mixed. The program reports that the user has been created correctly, but cannot log in with the specified user and password data. I also tried through the console in Portainer, but only superuser can be created from there. I reinstalled the container but no success. Where am I going wrong?! Can I have a bit of help?!

**Comment by pirate** [comment]
This is not supported right now. Only superusers are allowed. The reason is I provide paid ArchiveBox support/setup for bigger organizations, and that's really the only feature that they need / are willing to pay extra for.

It's not hard to enable this in the codebase if you need it for free, but I can't give it away for free 😉

**Comment by frizerabg** [comment]
Thanks for the comprehensive answer!

**Comment by pirate** [comment]
It varies depending on client and needs but our pricing model is available here: https://monadical.com/pricing-model

As of 2023-04 our dev/support contracts start around $100k

**Comment by pirate** [comment]
Note we have a new doc now outlining our consulting offerings: https://docs.sweeting.me/s/archivebox-consulting-services
