### ISSUE TITLE
Question: how to remove a particular entry from archivebox scheduling list?

### ISSUE THREAD

**Issue by hacback17** [ArchiveBox/ArchiveBox#1351]
I am a first time user of ArchiveBox, and I have added multiple entries in my ArchiveBox Scheduler. Later I realised that I want to remove one particular entry from the scheduler. How can I do it?

**Comment by pirate** [comment]
We don't have a native way to remove an individual entry from the CLI at the moment, it's a tricky problem because the file can be in a few different formats, can be edited directly by users and other programs, and not all the scheduler running methods are stateful (e.g. `--foreground` doesn't store a crontab at all).

Here are some options to accomplish what you need though:

---

### Option 1. locate the crontab file for you user and remove individual lines from there

We use `python-crontab` internally to create scheduled jobs (which in-turn uses UNIX's crontab system with a crontab file for your user). https://pypi.org/project/python-crontab/

```python
from crontab import CronTab

>>> c = CronTab(user=True)
>>> c.tabfile
>>> ... figure out where your crontab file is located by exploring more attrs on this object
```
Then edit/remove individual lines from that file, e.g. `/var/spool/cron/crontabs/username`

---

### Option 2. Clear the whole list and add back entries manually

```bash
# backup the list of schedule jobs to a file somewhere
archivebox schedule --show > ~/Desktop/schedule_backup.txt

# clear the whole list of scheduled jobs registered in the crontab
archivebox schedule --clear

# then add them back in manually from ~/Desktop/schedule_backup.txt
archivebox schedule --add ...
```

**Comment by hacback17** [comment]
Thank you for the guidance. it was very helpful.
