### ISSUE TITLE
How to navigate various snapshots of a single url?

### ISSUE THREAD

**Issue by ChillarAnand** [ArchiveBox/ArchiveBox#1377]
### Discussed in https://github.com/ArchiveBox/ArchiveBox/discussions/1376

<div type='discussions-op-text'>

<sup>Originally posted by **ChillarAnand** March  9, 2024</sup>
In archive.org, for a given url, we can see all the available snapshots and we can easily navigate to a specific date.

<img width="1280" alt="Screenshot 2024-03-09 at 18 58 25" src="https://github.com/ArchiveBox/ArchiveBox/assets/4463796/92a5cdf9-9fd1-4fb9-9903-0c28c47e7884">

In archivebox, I have millions of URLs and several hundreds of snapshots each.

How can I view all snapshots of a given URL chronologically?</div>

**Comment by pirate** [comment]
Wow millions is definitely up there! Highest I've seen amongst most non-corporate users is 200k. It's not really optimized for collections that big yet, so I applaud your efforts!

We don't have a way to browse snapshots over time yet because taking multiple snapshots of a single URL is sort of a kludge right now. We have better support coming this year though, once we move Snapshots to UUID-based ids instead of timestamp-based IDs.

Follow here for more info: https://github.com/ArchiveBox/ArchiveBox/issues/179

**Comment by pirate** [comment]
I'm going to close/merge this into #179 for now, as historical snapshot browsing will definitely be part of our eventual full multi-snapshot support! 👍
