### ISSUE TITLE
Bug: Container does not honor PUID/GUID environment variable. Installation fails complaining about being run as root.

### ISSUE THREAD

**Issue by sodamouse** [ArchiveBox/ArchiveBox#1379]
#### Describe the bug
When using the default docker-compose.yml file with docker-compose or podman-compose (rootless), the environment variables for PUID and GUID are not honored and installation exits complaining about being run as root. 

#### Steps to reproduce
- Download official docker-compse file
- Set PUID/GUID to the output of id -u and id -g (manually)
- docker-compose run archivebox init --setup

#### Screenshots or log output
compose file:
```yml
...
environment:
        - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name
        # - PUBLIC_INDEX=True               # set to False to prevent anonymous users from viewing snapshot list
        # - PUBLIC_SNAPSHOTS=True           # set to False to prevent anonymous users from viewing snapshot content
        # - PUBLIC_ADD_VIEW=False           # set to True to allow anonymous users to submit new URLs to archive
        # - ADMIN_USERNAME=admin            # create an admin user on first run with the given user/pass combo
        # - ADMIN_PASSWORD=SomeSecretPassword
        - PUID=3330
        - PGID=3331
```

error:
```bash
podman run --name=databases_archivebox_tmp42009 -i --pod=databases --label io.podman.compose.config-hash=123 --label io.podman.compose.project=databases --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=databases --label com.docker.compose.project.working_dir=/mnt/mpathh/{username}/databases --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=archivebox -e ALLOWED_HOSTS=* -e PUID=0 -e PGID=0 -v /mnt/mpathh/{username}/databases/data:/data --tty archivebox/archivebox:dev init --setup

[X] Error: Got PUID=0 and PGID=0 but ArchiveBox is not allowed to be run as root, please change or unset PUID & PGID and try again.
    Hint: some NFS/SMB/FUSE/etc. filesystems force-remap/ignore all permissions,
          leave PUID/PGID unset, disable root_squash, or use values the drive prefers (default is 911:911)
    https://linux.die.net/man/8/mount.cifs#:~:text=does%20not%20provide%20unix%20ownership
```

#### ArchiveBox version

```logs
I can't get version due to error preventing executing archivebox. But using latest docker image from 2024-03-13.
```

**Comment by pirate** [comment]
You have `-e PUID=0 -e PGID=0` above in the command you shared, which superseeds any values set in `docker-compose.yml`.

![image](https://github.com/ArchiveBox/ArchiveBox/assets/511499/8adae621-1c32-4515-9f8d-03892cff3dee)


Can you try again without those flags?

**Comment by sodamouse** [comment]
> You have these flags `-e PUID=0 -e PGID=0` above in the podman command you shared (which supersede any values set in `docker-compose.yml`).
> 
> ![image](https://private-user-images.githubusercontent.com/511499/312762888-8adae621-1c32-4515-9f8d-03892cff3dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA1MzgsIm5iZiI6MTcxMDQzMDIzOCwicGF0aCI6Ii81MTE0OTkvMzEyNzYyODg4LThhZGFlNjIxLTFjMzItNDUxNS05ZjhkLTAzODkyY2ZmM2RlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNTMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzdlOWNhODg0ODJmMGI2MjljOWFmYTMzOTg5ZmM2ZjE1YTExYjI4YTZkOGFhMTJlMDVlZGE5MGMzY2RhYWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ym7lX1ohQjuuOja11ODRCMWA9MQSJYmwBy4v-iOCmzU)
> 
> Can you try again without those flags?

I'm not the one who is inserting those. That command is what is generated when I run docker-compose up.

**Comment by pirate** [comment]
Whatever is generating that command is your culprit, it's not controlled by archivebox. 

I haven't used podman much, but it looks like it could probably be a podman configuration thing?

**Comment by sodamouse** [comment]
It's possible but i don't have any control over it. Podman is rootless, so anything that get  executed is not actually being run as root, but having PUID=0 in the container throws off archivebox i suppose.

**Comment by pirate** [comment]
ArchiveBox always drops down to a non-privileged user, we don't allow running it as root for security reasons.

If you pass a valid, non-root `PUID` (ideally `>500`, lower UIDs may behave strangely), it will set the `archivebox` user use that uid and drop down to that user to run the archiving processes.

Trying to explicitly set `PUID` `=` `0` is prohibited because the underlying archiving processes are not safe to run as root (too much shell execution->downloading->parsing [RCE](https://www.cloudflare.com/learning/security/what-is-remote-code-execution/) escalation risk).

https://github.com/ArchiveBox/ArchiveBox/wiki/Security-Overview#do-not-run-as-root

**Comment by sodamouse** [comment]
You reasoning is sound and i understand it, however this makes the docker solution unusable in my environment. I will look into how to disable this check.

![WindowsTerminal_r8aP8onK6R](https://github.com/ArchiveBox/ArchiveBox/assets/112235696/94c48534-a912-4da3-a34d-af89ada74083)

**Comment by pirate** [comment]
As a workaround you can use docker exec instead of docker run / modify the entry point to not run ./bin/docker_entrypoint.sh. Youll need to also add --user=archivebox manually or user: archivebox.

**Comment by pirate** [comment]
I can't find any reference to `PUID`/`PGID` tampering in the `podman-compose` codebase, are you sure there isn't something else in your setup that could be causing this?

https://github.com/search?q=repo%3Acontainers%2Fpodman-compose+puid&type=code

What is the PUID/PGID you're intending to set (i.e. the result of `$(id -u)` in your screenshot)?

At this point I'm just genuinely curious how those vars are getting set, because as far as I know they're not "part of docker" they're just a convention created by linuxserver.io, so I'd be very surprised to see a docker alternative like podman or a container management environment like Proxmox/TrueNAS/Cloudron/etc. forcibly setting them.

Are you running in a special managed hosting environment of some kind or using an OS/container management solution that I could look into?

I'm going to close this for now since it's not really a problem with ArchiveBox per-se, but I do love devops spelunking and I am still curious, so if you're willing to share more about your setup I'd be happy to keep investigating and help find a solution in the comments here.

**Comment by sodamouse** [comment]
Hi, the issue is that this setup is not managed by me. It's managed by a provider, so unfortunately i can't provide you info beyond guesswork. All I can say is that I am not adding `PUID=$(id -u)` myself, and that I believe podman is indeed being run inside docker.
