### ISSUE TITLE
Discussion: New logo designs

### ISSUE THREAD

**Issue by jorlogicus** [ArchiveBox/ArchiveBox#178]
Type:

 - [ ] General Question or Disussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

**How badly do you want this new feature?**
 - [ ] It's an urgent deal-breaker, I cant live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually
 - [ ] I'm willing to contribute to development

Greetings, I'm here today to offer my services. As a graphic designer in development and an open source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process (of course) is totally free and we would be working together to create the design that fits best with your project. Of course, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colors, shapes, etc. 

Sorry for disturbing if this is not the proper channel, best regards.

**Comment by pirate** [comment]
Wow, that would be awesome! Thanks for the offer @jorlogicus!

Some logo requirements:
 - should be relatively minimal, easy to recognize at small sizes (e.g. as a favicon / app icon)
 - should be intuitively visually related to the name
 - should not use the building icon / columns that https://archive.org uses in their logo
 - public domain/licensed fonts & icons only

I like the physical "archive box" style icon we have now because it's intuitively visually linked to the name ArchiveBox, it would be nice to incorporate it into the new logo somehow, but not required if you have other ideas.

Let me know your thoughts!

**Comment by jorlogicus** [comment]
Hello, sorry for the delay, I'm starting to design a few sketches and will come back to you as soon as I finish them. Also will check vectorstock.com to see if anything is usable for this purpose, I don't believe I will be using paid icons or fonts for this so don't worry.

**Comment by jorlogicus** [comment]
Ok so here it begins, these are a few sketches I just finished (sorry again for the delay, things are pretty messed up here in Venezuela with those blackouts right now). Want to know your opinion about them
![Recurso 1](https://user-images.githubusercontent.com/46901656/56230699-d2ae5e80-604a-11e9-8d1b-c0003903b9e2.png)

**Comment by jorlogicus** [comment]
Greetings everyone. Things have been pretty messed up lately around here but here I am to continue with this logo. Would you like me to resume my work? If yes, what were your opinions on the last sketches I sent?

**Comment by pirate** [comment]
@jorlogicus le'ts chat sometime, I'd love to see how I can help. I have some friends in Venezuela who got out to Colombia and managed to find tech work there.

Do you use [hangouts](https://hangouts.google.com/chat/person/111079193312754413701)? WhatsApp also works for me: +15037419577.

**Comment by jorlogicus** [comment]
@pirate that's very kind of you, I'll text you on WhatsApp for sure, thanks! 

About the logo, do you want to continue with the process?

**Comment by pirate** [comment]
We can continue but let's have a quick call first to discuss the goals and design style.  Also I'd love help designing https://archivebox.io to be nicer, I think that might be more important than a new logo at this stage. I can pay for your time as well.

One small comment is that I'd like to keep the red/white colors if possible rather than switching to blue.  Also the "box of files" imagery to match an actual cardboard archive box is a good direction to go in. I think the logo right now is intuitive because it's what people image when they think of a physical archive box, so it would be nice to keep that symbolism.

Thanks again!

**Comment by pirate** [comment]
Going to close this for now because I kind of like the current logo and it's built up a bit of reputation at this point :)
