### ISSUE TITLE
Bugfix: All tags automatic delete after add a new URL

### ISSUE THREAD

**Issue by imlonghao** [ArchiveBox/ArchiveBox#421]
#### Describe the bug

I added some URL via the web interface, then I manually added tags for some of them.
After that, I add a new URL, then, all tags disappear.

#### Steps to reproduce

1. Setup ArchiveBox environment via Docker
2. Add a URL
3. Add tag to the URL
4. Add another URL
5. Tags disappear.

#### Software versions

 - OS: ArchLinux
 - ArchiveBox version: v0.4.9 (Docker Version)
 - Python version: 3.8.5
 - Chrome version: 84.0.4147.105

**Comment by pirate** [comment]
Ah this is because the UI only saves the tags to the SQLite db, and not to the main index.json. We're going to remove the index.json anyway in a future version, so rather than fix this bug by adding 20+ lines of workaround code, I think we'll probably just leave it broken until the next version when it becomes irrelevant.

For now I recommend adding your tags before you import the URLs, or don't use tags until v0.5. Sorry for the trouble.

**Comment by pirate** [comment]
This is fixed in the latest versions.
