### ISSUE TITLE
Bug: ArchiveBox crashes when encountering wget-generated filenames that are too long

### ISSUE THREAD

**Issue by danst0** [ArchiveBox/ArchiveBox#549]
Hi,

I get a filename too long error after an import. Could someone please help?

Daniel
![Bildschirmfoto 2020-11-25 um 08 20 53](https://user-images.githubusercontent.com/1544506/100195125-29eb0500-2ef7-11eb-9e70-761ba13673ce.png)

**Comment by pirate** [comment]
It is what it says on the tin :)

That filename is indeed too long, you'll have to remove that URL from your archive and delete the file or live with the error. It's a hard limitation of using the filesystem for archiving with the WGET extractor.

**Comment by danst0** [comment]
ok.
Shouldn't there be something preventing the generation of these long names in the first place. If I re-archive this link I will have the same result again?
If there is this limitation on the filename length (I think I am on ext4 so 255 characters). Does it really make sense to simply use the url components to name the files? should archivebox use some kind of hash?

Daniel

**Comment by pirate** [comment]
You're the first person to hit this edge case in 5 years so I'm not super keen on adding code surface area to catch it, especially when it varies from filesystem to filesystem. This limitation also only exists for the wget extractor which uses the url->filesystem mapping (which is fundamentally difficult and flawed for many reasons beyond just filename length), none of the other extractors have this problem. If you want to re-archive this link (or others like it with super long filename components) you can turn off the wget extractor with `archivebox config --set SAVE_WGET=False`. It should be fine because we're not relying as heavily on the wget extractor these days anyway. Singlefile, PDF, Screenshot, can make up for the lack of wget.

**Comment by danst0** [comment]
Ok.

**Comment by pirate** [comment]
Actually I just double-checked the code path and this error will be gone in 0.5.

Update on the next release and you should be good to go. We removed the filesystem checks for ArchiveResults entirely in #525 and as a side effect it'll never need to call this failing `.exists()` check to render the UI.

**Comment by mAAdhaTTah** [comment]
FWIW, this _may_ be a Windows-only issue. I vaguely recall early versions of npm having this issue with its naive dependency resolution algorithm.

**Comment by danst0** [comment]
probably not. I have archivebox running on docker on ubuntu

**Comment by clb92** [comment]
For what it's worth, I'm having the same problem right now on a Docker install of latest ArchiveBox image. Host system runs Unraid and uses XFS, if that matters.

From a normal user's perspective, ArchiveBox just seems to stop working randomly, which is terrible UX. I'm a firm believer that ArchiveBox should (at a minimum) catch the error gracefully and just skip the URL, instead.

This is all the log I could get easily:
![Screenshot](https://github.com/ArchiveBox/ArchiveBox/assets/4537419/f12dcf32-9404-4350-869c-6a110a2728a8)

**Comment by pirate** [comment]
We can definitely catch the error and delete the file at the archivebox layer. It's not super common but at this point I've seen this issue ~4 times in the wild so it seems fair to add a workaround now.

For context: wget auto-detects the OS and filesystem and attempts to truncate/remap characters differently based on the limitations of each OS. I suspect they don't have a case to explicitly handle XFS, so that may be how you ended up with a path that long. 

Wget's URL -> path mapping logic is frustratingly complex and non-deterministic from ArchiveBox's perspective. It means we can never predict where exactly wget will write its output files ahead of time, we have to wait for it to run and then scan the entire directory tree to see what it did. (See here https://github.com/ArchiveBox/ArchiveBox/issues/1373 for another example of wget's URL -> path mapping weirdness.)

I try very hard not to write bespoke workarounds for each filesystem and URL edge case, but rather choose the safest behavior that works across all, but this is an example of that approach failing.

What do you think ArchiveBox should do when it encounters an illegally-long filepath created by wget? It seems sad to just delete it, it may have downloaded correctly and contain real data. If we attempt to rename/move it somehow it will break the integrity of the wget download because the relative paths within wont work anymore, so maybe hard crash or deleting are the only reasonable options?

**Comment by clb92** [comment]
Thank you very much for the context and explanation (though, it looks like that comment disappeared again just now).

My use case is that I have the browser addon continuously add every page I visit to ArchiveBox. The biggest annoyance for me, currently, is that I have to babysit ArchiveBox and manually go in and remove a URL from ArchiveBox if/when it stops working, so that I can keep it working. It's not a stable setup. I would rather have a few URLs that can't be archived properly than having my setup break every few days, needing manual intervention every time.

But I recognize that others may be using Archivebox in a different way, perhaps only manually adding URLs to be crawled and archived a lot more thoroughly.

Perhaps what's needed is a way to mark URLs being added as "not important", aka. "ignore errors and just skip whatever fails"?

Just throwing ideas out there.

**Comment by pirate** [comment]
I deleted my comment because it was wrong, it turns out wget is not creating bad paths, it's my workaround logic checking for a path that cannot exist that's causing the error.

I just fixed it on `:dev` 🚀 f770bba3

**Comment by clb92** [comment]
Sorry, but I can't test out :dev it seems, since now I'm getting the error ```Could not find profile "Default" in CHROME_USER_DATA_DIR``` right after updating. I haven't changed anything in my config. CHROME_USER_DATA_DIR is set to None.

**Comment by pirate** [comment]
Oh thanks for reminding me of that, some other users reported it too. I'll change it to be a warning by default instead of an error so it's less annoying.
