### ISSUE TITLE
Detect failed extractors by checking that output file is above a minimum threshold size

### ISSUE THREAD

**Issue by bash-stack** [ArchiveBox/ArchiveBox#604]
since the update/add loop only checks if a file is present after TIMEOUT time ,

the checks should try the `file` command and see f the file is healthy  , 
and maybe a "Minimum pdf result size" would be cool ( so a 10kb pdf could beconsireded empty)

a good command to find  many failed URLs was :

```bash
echo "reindexing empty titles , missing screens or pdf"
(
	echo "SELECT url FROM core_snapshot WHERE title is NULL ;" | sqlite3  data/index.sqlite3;
	(
		for dir in $(ls data/archive/* -1d); do
		    REINDEX=NO
		    file $dir/output.pdf | grep -q PDF || REINDEX=YES
		    file $dir/screenshot.png | grep -q PNG || REINDEX=YES
		    [[ "$REINDEX" = "YES" ]] && {  
                url=$(cat $dir/index.json|jq .url | cut -d\" -f2)
                echo reindex $url >&2
                echo $url
            }
        done | shuf
    )
) | awk '!x[$0]++' | while read LINKME
do [[ -z "$LINKME" ]] || docker exec -it archivebox_archivebox1 su -s /bin/bash -c " NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt archivebox update $LINKME " archivebox ) ; echo "$result" |grep -v -e ^$ -e "archivebox server" -e "Web UI"; echo "$result"|grep -q "0 links had errors" || { echo reindexing "$LINKME  >&2 ;echo $LINKME >> /tmp/failed } ;   echo "$result" |grep -q -e django.db.utils.OperationalError -e "is locked" && { echo reindexing "$LINKME $linkb $linkc" ; ( (echo ;echo "$LINKME";echo ) > /tmp/failed )& echo .. ; } ; }  ; done
```

**Comment by pirate** [comment]
It's an interesting idea. Do you find many empty PDFs/screenshots in practice? This is not something I've seen happening before. Can you post a few examples of those and the log output it emitted when generating them? I suspect there's some underlying error like the TIMEOUT being set too low.


If this issue is widespread I'd rather implement this in python immediately after the extractor runs, instead of as a separate async process in bash.

**Comment by bash-stack** [comment]
happened under high load and low ram circustances , the pdf/screen sometimes only contains date and url .. (blank hml body)
the fancy bar index said "success"

also the loopp should check if the child pid is still running and kill ( sometimes many node and some chromium processes were leftover)

**Comment by pirate** [comment]
> Can you post a few examples of those and the log output it emitted when generating them?

**Comment by pirate** [comment]
In the new version I check that the file is at least 1 byte. I don't want to make it any more granular than this because otherwise it'll flag valid empty 200 responses (yes, that is a thing) as failing URLs.

I'll consider adding more healthchecks in the future for extractor output, but for the moment I think this is enough.
