### ISSUE TITLE
Question: Obey uBlock filter rules?

### ISSUE THREAD

**Issue by winteriscariot** [ArchiveBox/ArchiveBox#630]
Is it possible for any archive methods to obey uBlock filter rules added via the 'picker' utility in uBlock (you can find the full list of them in the 'My Filters' tab in uBlock settings). This would be for uBlock installed in the chrome profile identified in the config.

My other option would be to process the resulting archived files separately to remove the indicated elements, but if archivebox is using chrome to capture the website anyway figure it might be worth not pulling those elements at all (if possible)

thanks!

**Comment by winteriscariot** [comment]
Issue #211 mentions being able to use ublock:

>  Using a chrome extension like Ublock Origin and/or Ghostery (this is already possible)

however it doesn't appear to be obeying user filters

**Comment by jacobwhall** [comment]
I would also like to get this set up. According to #211 that you linked, this can be achieved by [using the CHROME_USER_DATA_DIR option](https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#chrome_user_data_dir). You might also find #516 helpful. Good luck!

**Comment by pirate** [comment]
This is a valid question, but I'm actually going to close this in favor of keeping the discussion here: https://github.com/ArchiveBox/ArchiveBox/issues/211, because I already had uBock Origin + Ghostery in mind for the implementation of that ticket.

Using `CHROME_USER_DATA_DIR` and installing the extension in that profile works for some people, but is buggy/impossible on other OS/browser combos.

I have a good solution in mind (involving a config option for chrome extensions + a profile to run) but it is blocked by:

1. an upcoming event-sourcing refactor in >=v0.7 to allow for faster worker-pool based parallel archiving (3-6 months)
2. addition of the `playwright` extractor dependency in favor of the old chrome-headless CLI / pupppeteer approach (2-4 months)

If you hit "subscribe" over on https://github.com/ArchiveBox/ArchiveBox/issues/211 I'll notify you when we get close to it.

If you can think of any quick-and-dirty solutions to make this easier that would get us there before the `playwright` implementation, I'm all ears, please suggest them over on #211!
