### ISSUE TITLE
Feature Request: search by status in web ui

### ISSUE THREAD

**Issue by khimaros** [ArchiveBox/ArchiveBox#647]
## Type 

 - [ ] General question or discussion
 - [x] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

i have an enormous number of links to archive and would like to be able to search for the ones which have already been archived in the web ui.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

typing `status:valid` or `status:archived` in the ui would display the relevant snapshots only.

## What hacks or alternative solutions have you tried to solve the problem?

this can be accomplished on the command line:

```
$ archive box list --status archived
```

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
I've sort of implemented this in c98053a.  It's not exactly what you're asking for since it's not technically the Snapshot status, it's the ArchiveResult status (aka the individual extractor outputs under a Snapshot). It should be tricky to allow filtering by Snapshot status directly since theres actually no db field for it, it's a derived property based on some heuristics and cant be queried directly.

It should be out with the next release v0.6 soon. You can also try it early by installing directly from the dev branch.
```bash
pip install "git+https://github.com/ArchiveBox/ArchiveBox.git@dev"
```

Comment back here if that solution doesn't work / you absolutely need Snapshot status as originally described and we can discuss further.
