### ISSUE TITLE
Question: Does Archivebox 0.5.6 still output static index.html?

### ISSUE THREAD

**Issue by drpfenderson** [ArchiveBox/ArchiveBox#653]
I just noticed that the old `index.json` and `index.html` that were in my root archive directory have been renamed `_old`, but I'm not seeing a new version being output with my archive in the most recent 0.5.6 version. If I recall, the `index.json` was phased out in favor of the sqlite3 method. Has the static html been phased out for the server, or some other method, in the newer version? Is it perhaps hidden behind a flag or config option I'm missing?

**Comment by ekiel** [comment]
`docker-compose run archivebox list --html --with-headers > index.html`

This should work and I'm testing it now...

**Comment by drpfenderson** [comment]
Asked and answered! Thanks a ton @ekiel

**Comment by pirate** [comment]
We're pushing towards the server for security reasons. Static HTML is unfortunately very risky because replayed JS can make arbitrary requests to other files on your filesystem, including reading your whole index and all the other sites you've archived. The server aims to fix that by serving snapshot content with headers to lock down XSS/CSRF/CSP/etc.
 
You can still generate static html/json/csv main indexes with the `archivebox list` command, but they'll no longer be automatically updated. For now, the individual snapshot detail index pages are still static html however, and are still kept up-to-date, unlike the main index.

```bash
docker-compose run archivebox list --html --with-headers > index.html
docker-compose run archivebox list --json --with-headers > index.json
docker-compose run archivebox list --csv > index.csv
```
