### ISSUE TITLE
Failed to archive link: UnicodeEncodeError: 'gbk' codec can't encode character '\u25be' in position  9443: illegal multibyte sequence

### ISSUE THREAD

**Issue by Littlegolden** [ArchiveBox/ArchiveBox#674]
similar with #32, but it happens when archiving the site:

![image](https://user-images.githubusercontent.com/35162802/112638479-42a20200-8e7a-11eb-96c8-ddef583435a4.png)

**Comment by pirate** [comment]
I think this is a different issue, can you share what the URL is that you tried to archive?

Also please post the full output of `archivebox --version`.

**Comment by pirate** [comment]
I think it's due to windows not defaulting to UTF-8 for file writes.

There's a PEP to fix it, but it's not proposed to land until 3.10: https://discuss.python.org/t/pep-597-enable-utf-8-mode-by-default-on-windows/3122

In the meantime can you try setting the `PYTHONLEGACYWINDOWSSTDIO=utf-8` environment variable and running it again.

Related issue: https://github.com/ArchiveBox/ArchiveBox/issues/678
