### ISSUE TITLE
Bug: Missing arm images for latest tag

### ISSUE THREAD

**Issue by Glutamat42** [ArchiveBox/ArchiveBox#691]
#### Describe the bug
I tried to setup ArchiveBox on my odroidxu4 but it failed because there are currently no arm versions of the latest tag. Using another tag (tested with dev) works fine, just like building the image locally on my odroid. This is counter intuitive since latest is the default tag and also the one used in the docker-compose.yml file.

- There are no arm versions for latest listed on hub.docker.com
- The pulled image for latest is an amd64 build (docker image inspect ...)

Besides that, this project looks amazing :)

**Comment by pirate** [comment]
Thanks for reporting.

Try again in about 15min, I just fixed the Github Action that tags our docker images to update latest: https://github.com/ArchiveBox/ArchiveBox/commit/26f591fd788ae70aa6fb22125caa056f17817830

Comment back here if it's still not working and I'll reooen this issue.

**Comment by Glutamat42** [comment]
Still no arm images for latest.

https://hub.docker.com/layers/archivebox/archivebox/latest/images/sha256-34ecbf7cdbed9d6ddc47c50ba23440edbef174a7859aa5341f7e9d9d78ac4e88?context=explore

**Comment by pirate** [comment]
Ok so it turns out `latest` is usually only updated on new numbered releases, and on the last numbered release we did not have arm builds automated yet, so that's why it wasn't attached with an arm build.

I can force it to update so that it's on the latest commit with arm/amd64/x86, and I just tested that and it works, so it's temporarily ahead of the latest release right now:

![image](https://user-images.githubusercontent.com/511499/113627243-39aaf080-9631-11eb-9b9d-49cae860d245.png)

However, I'm going to be changing it back to the old behavior because I don't really want people pulling the latest image directly from the dev branch, I'd rather it be the last stable release.

**Comment by cpmsmith** [comment]
For anyone else still looking at this: the version mentioned above is now just tagged [`sha-5009a84`](https://hub.docker.com/layers/archivebox/archivebox/sha-5009a84/images/sha256-0d35cac0d9bf13ffab394259bb06b1ad56e0ff34383d390c2572e967fb76317b?context=explore), and `latest` has been pushed to [another version with no ARM builds](https://hub.docker.com/layers/archivebox/archivebox/latest/images/sha256-be751c3af77a843ab49e6dbb11a6aae7584ea7c3ae6b0d913706c044f95e331e?context=explore). However, the **[`master` tag does have ARM builds](https://hub.docker.com/layers/archivebox/archivebox/master/images/sha256-c13d5d0f3e664fabb2ee73e895f76ea2a93cf5a7b73e6cc68256054209451134?context=explore)**.

**Comment by pirate** [comment]
You should use the `0.6.2` tag on arm, not `latest`, there's an open issue on the library we use to generate the tags that's fixing the arm latest problem.
