### ISSUE TITLE
Discussion: Serve in a subfolder

### ISSUE THREAD

**Issue by danisztls** [ArchiveBox/ArchiveBox#724]
Current paths are:
```
mydomain/public/...
mydomain/private/...
mydomain/static/...
```

I suggest optionally having it under a subfolder to make it easier to put ArchiveBox under a reverse proxy like Nginx.
```
mydomain/archivebox/public/...
mydomain/archivebox/private/...
mydomain/archivebox/static/...
```

Is it feasable?

**Comment by pirate** [comment]
It's pretty difficult, but not impossible, there are a lot of `/relative` urls all over the codebase. A bunch are in the static.html too, so it's hard to change them after-the-fact since they wouldn't be re-rendered after you reconfigure it automatically.

**Comment by pirate** [comment]
Reopening because I do want to allow this to be done eventually when I have time, it just probably wont be done by the next version or two.

**Comment by FraMecca** [comment]
What about this:
https://ubuntu.com/blog/django-behind-a-proxy-fixing-absolute-urls

**Comment by mhfowler** [comment]
fwiw this would be helpful for the purpose of packaging archivebox as a yunohost package, something I've been working on. discussed here https://forum.yunohost.org/t/nginx-config-for-path/16887

**Comment by ss89** [comment]
i'd also like to see this feature

**Comment by pirate** [comment]
Doing this breaks a surprising amount of things because of how relative paths are written statically to the filesystem in the index.json/html files. It's fixable with rewriting in a Django middleware but it's complicated and there are a lot of edge cases and it's still low on my personal priority list.

**Comment by pirate** [comment]
I think I'm actually going to close this as `wontfix` because of the security issues. ArchiveBox really should only be hosted from a dedicated subdomain, because it's extremely risky to rehost archived JS on a domain shared with other sites. It breaks CSRF and many other web security mechanisms to have untrusted content and JS on a domain shared with other apps.

**Comment by sasasqt** [comment]
well, if you insist, here is the nginx code that redirect yourdomain/archivebox/ to 127.0.0.1:8000

```
http {
    map "$http_referer$request_method" $archivebox_post {
        default 0;
        "~.*/archivebox/.*POST" 1;
    }
    map "$http_referer$request_method" $archivebox_get {
        default 0;
        "~.*/archivebox/.*GET" 1;
    }
    server {
        location / {
            root   html;
            index  index.html index.htm;
            if ($archivebox_post) {
                return 307 /archivebox/$request_uri;
            }
            if ($archivebox_get) {
                return 301 /archivebox/$request_uri;
            }
        }
        location /archivebox {
            return 302 /archivebox/;
        }
        location /archivebox/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect / /archivebox/;
            proxy_pass http://127.0.0.1:8000/;
        }
```
