### ISSUE TITLE
Feature Request: Add env var options `ARCHIVEBOX_USERNAME` and `ARCHIVEBOX_PASSWORD` to initialize admin user on first run without prompting

### ISSUE THREAD

**Issue by marco10x15** [ArchiveBox/ArchiveBox#734]
I have succesfully deploied via docker using portainer a container on my Synology NAS.
I can access the web gui but i haven't found in the documentation the Admin Password to be used to acces.
How can I find the password or what ENV variable I must set up?
Thank.
Marco.

**Comment by pirate** [comment]
Run `archivebox manage createsuperuser` using the CLI.

**Comment by mhfowler** [comment]
I'm currently working on creating a [yunohost package](https://yunohost.org/en) for archivebox, and this feature will also be needed for that. 

Or some other way, which I can supply an initial admin and password for archivebox during setup (perhaps as CLI arguments?), without an interactive prompt with the user (since the app is installed via a GUI, without a user directly interacting with the terminal)

**Comment by mhfowler** [comment]
for now I was able to achieve what I needed using expect, but having CLI args for archivebox would probably be cleaner. e.g.

```
usr/bin/expect<<EOF
set timeout -1
spawn sh -c "cd $datadir && archivebox manage createsuperuser --username $admin --email $admin_mail"
match_max 100000
expect "*?assword: "
send -- "$password\r"
expect "*?assword (again): "
send -- "$password\r"
expect eof
EOF
```

**Comment by pirate** [comment]
Those are the default Django password validators kicking in (see settings.py) to try and keep people safe, I suppose we can disable them with another env var or specifically in the case that the pass is loaded via env vars.

**Comment by solarchemist** [comment]
This would be good for Ansible also.

I tried using the expect plugin (which has worked for me before when no other options were available), and it actually worked, but only during the first run of the playbook:
```
- name: Create Archivebox superuser account
  ansible.builtin.expect:
    command: archivebox manage createsuperuser
    timeout: 10
    responses:
      'Username': "{{ archivebox_admin.user }}"
      'Email address': "{{ archivebox_admin.email }}"
      'Password': "{{ archivebox_admin.pwd }}"
      'Password (again)': "{{ archivebox_admin.pwd }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    chdir: "{{ archivebox_pwd }}"
```

For some reason beyond my understanding, subsequent runs of this task would just freeze indefinitely (this is not a request for support, just noting the weird behaviour and moving on).

Anyway, so that's another reason why it would be great to be able to set the admin user non-interactively. The expect command can be rather fragile at times.

**Comment by pirate** [comment]
Note that you can also insert a USER row directly into the `index.sqlite3` db as a temporary hacking (instead of using expect).

**Comment by solarchemist** [comment]
Thanks for the suggestion! If I get the time, I'll look into doing that.

PS. I just pushed [the Ansible role I used to install ArchiveBox to Codeberg](https://codeberg.org/ansible/archivebox). The role is quite tailored to my needs, but the more Ansible roles, the merrier, right? :-)

**Comment by pirate** [comment]
For people here looking for a temporary solution, I posted instructions on how to insert a User row directly into the SQLite3 DB here: https://github.com/ArchiveBox/ArchiveBox/issues/928#issuecomment-1075758078.

**Comment by Nezteb** [comment]
Chiming in to say that I'd love this feature. The SQLite workaround is cool but I'd rather not mess with that in case the implementation eventually changes.

I'm deploying to https://fly.io/ and for most services I host there, I just need a single `Dockerfile` and a `fly.toml` without ever needing to start a remote shell to run a startup/config command.

**Comment by pirate** [comment]
This is done and merged into `dev`, thanks @benmuth!

I'll update the docs to reflect the new feature.  For anyone that wants to use this immediately you can run the `dev` branch like so: https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch
