### ISSUE TITLE
Bug: Re-Snapshot removes URL fragment

### ISSUE THREAD

**Issue by FliegendeWurst** [ArchiveBox/ArchiveBox#748]
#### Describe the bug
When re-snapshotting a URL, the URL fragment is overwritten with a timestamp.

#### Steps to reproduce
1. Archive (e.g.) `https://github.com/microsoft/vscode/issues/3884#issuecomment-230912738`
2. Re-Snapshot the URL
3. Actual URL now archived looks like `https://github.com/microsoft/vscode/issues/3884#2021-05-14T16:20:52+00:00`
4. Observe that the relevant comment is not saved

#### Screenshots or log output
see above (if you need screenshots/logs for this issue, I can provide them)

#### ArchiveBox version
ArchiveBox v0.6.2, using the docker container
(full output is not relevant to this issue, I believe)

**Comment by pirate** [comment]
Yeah this is a known shortcoming of how re-snapshotting is implemented currently. There is no fix, you just have to wait for first-class snapshot support to be implemented.

Please subscribe to this issue for updates: https://github.com/ArchiveBox/ArchiveBox/issues/179

Closing this for now because it's a subset of what we're tracking in the other issue and it's easier for everyone to follow one issue about this.
