### ISSUE TITLE
Question: Integrating Archivebox into my workflow

### ISSUE THREAD

**Issue by zblesk** [ArchiveBox/ArchiveBox#776]
Hello, 

there are a few things I'd like Archivebox to do, as part of my personal infrastructure and workflow. 
I understand that the HTTP API won't be here anytime soon, so I will work around that.

These are the 3 things I need to do: 
1. adding new links to Archivebox as my system ingests them.
2. for any link, answer the question "do I have this link archived?" and if yes, also returning the links to the archived version(s).
3. adding the text of the downloaded pages (article view only) to my search index

I think I can fix #1 by creating a txt endpoint that will contain the links to be archived, and having Archivebox fetch from that. 
For #2 and #3, I have looked at the DB briefly. 
Seems I can use `core_snapshot` to fetch a list of URLs I have in my archive. 
But how do I find which kinds of archival were successful? Is it somewhere in the DB, or do I have to crawl the filesystem and check "manually"? 

And what about the URLs? Will they always be in the form of `archive/<folder name>/readability/content.html` (where the last 2 parts are specific for each archive type)?

Is there anything else I should keep in mind? 

Thank you!

**Comment by pirate** [comment]
1. `archivebox add ./path/to/links.txt`
2. `archivebox list --csv=timestamp,is_archived 'https://example.com/url/to/check' | grep true`
3. `cat ./archive/<timestamp>/**/*.{txt,html,htm} | <cmd to add to search index>`

> But how do I find which kinds of archival were successful? Is it somewhere in the DB, or do I have to crawl the filesystem and check "manually"?

You can use either the CLI `archivebox list --csv=timestamp,is_archived 'https://example.com/url/to/check' | grep true` or you can check the SQL db using the `core_archiveresult` table. It contains all the results you see on the `Log` page in the UI, and you can select using the foreign key to the snapshot and look for any succesful `ArchiveResult` entries (which means it's succeeded in archiving).

> And what about the URLs? Will they always be in the form of `archive/<folder name>/readability/content.html` (where the last 2 parts are specific for each archive type)?

Yes, however some are stored directly in the root of the archive subfolder like: `archive/<folder name>/singlefile.html` (for legacy reasons).

> Is there anything else I should keep in mind?

ArchiveBox has full-text indexing built in already, why not call out to that directly instead of building your own index on top of it?

`archivebox list --filter-type=search 'some text to search'`

This uses [Sonic](https://github.com/valeriansaliou/sonic) if you have it [set up](https://github.com/ArchiveBox/ArchiveBox/blob/dev/docker-compose.yml#L30), or `ripgrep` as the fallback if you don't have Sonic enabled.
