### ISSUE TITLE
Feature Request: Link directly to page position or highlighed selection

### ISSUE THREAD

**Issue by infogulch** [ArchiveBox/ArchiveBox#834]
## Type 

 - [x] Propose a brand new feature

## What is the problem that your feature request solves

As a user, I would like to be able to share a particular location or selection on an archived page so that someone following the link will go directly to the relevant portion of the page without having to scroll or search manually.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Make a selection on the displayed page, which updates the url bar with a fragment. Copying that url and navigating to it in a different window would scroll to and highlight the selection again.

## What hacks or alternative solutions have you tried to solve the problem?

The archive.is public archive supports this feature in two modes:

* Link to percentage down the page: http://archive.is/FWVL#40%
* Link to a specific selection in the page: http://archive.is/FWVL#selection-1493.0-1493.53

See: https://archive.is/faq

## How badly do you want this new feature?

- [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute [dev time](https://github.com/ArchiveBox/ArchiveBox#archivebox-development) / [money](https://github.com/sponsors/pirate) to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
To be honest I am probably not going to implement this, as it would involve injecting JS into replayed pages, which is a whole pandoras box that I don't want to open for as long as possible.

**Comment by infogulch** [comment]
That's a reasonable judgement call, thanks for considering.

**Comment by infogulch** [comment]
For future reference, I've copied some of the js of the archive.is implementation of this feature below. Based on a quick skim, `scrollToHash()` seems to work by interpreting the location hash (e.g. `#selection-1493.0-1493.53`) as two document locations (e.g. `1493.0` and `1493.53`) where the first part of each location (`1493`) is some bit-swizzled encoding of a path taken during a walk of all nodes in the document, and the second part (`53`) is the offset in the identified text node where that location begins/ends. Two of them give you a start and end point to remake the selection. Pretty neat idea, though the way `pos` is updated globally in a recursive descent through the document feels suspect to me.

There's no way this would be stable if the page were ever changed, but luckily these are archived pages we're talking about here. That said I can really see what you mean by "finnicky" 🤣.

I guess another consideration would be how this kind of "selection url" would work across different archive formats. The holy grail would be for such a selection link to translate across formats (e.g. warc/pdf/plain text) and degrade gracefully in the absence of the original format, but maybe that's setting the bar a bit high (like, geostationary orbit high 😅).

<details>

```js
function updateShareLinks() {
  var shortlink = "http://archive.is/FWVL";
  var re = new RegExp(shortlink.replace(".", "\.") + "(#selection-[0-9.-]+)?");
  var adr = document.location.hash.match(/(selection-\d+\.\d+-\d+\.\d+)/);
  document.getElementById("SHARE_SHORTLINK").value = document.getElementById("SHARE_SHORTLINK").value.replace(re, adr ? shortlink + document.location.hash : shortlink);
  document.getElementById("SHARE_MARKDOWN" ).value = document.getElementById("SHARE_MARKDOWN" ).value.replace(re, adr ? shortlink + document.location.hash : shortlink);
  document.getElementById("SHARE_HTMLCODE" ).value = document.getElementById("SHARE_HTMLCODE" ).value.replace(re, adr ? shortlink + document.location.hash : shortlink);
  document.getElementById("SHARE_WIKICODE" ).value = document.getElementById("SHARE_WIKICODE" ).value.replace(re, adr ? shortlink + document.location.hash : shortlink);
}
function findXY(obj) {
  var cur = {x:0, y:0};
  while (obj && obj.offsetParent) {
    cur.x += obj.offsetLeft; // todo: + webkit-transform
    cur.y += obj.offsetTop; // todo: + webkit-transform
    obj = obj.offsetParent;
  }
  return cur;
}
function findXY2(obj, textpos) { // it could reset selection
  if (obj.nodeType==3) {
    var parent = obj.parentNode;
    var text = document.createTextNode(obj.data.substr(0, textpos));
    var artificial = document.createElement("SPAN");
    artificial.appendChild(document.createTextNode(obj.data.substr(textpos)));
    parent.insertBefore(text, obj);
    parent.replaceChild(artificial, obj);
    var y = findXY(artificial);
    parent.removeChild(text);
    parent.replaceChild(obj, artificial);
    return y;
  } else {
    return findXY(obj);
  }
}
var prevhash = "";
function scrollToHash() {
  if (document.location.hash.replace(/^#/, "")==prevhash.replace(/^#/, ""))
    return;
  prevhash = document.location.hash;
  if (document.location.hash.match(/#[0-9.]+%/)) {
    var p = parseFloat(document.location.hash.substring(1));
    if (0 < p && p < 100 /*&& p%5 != 0*/) {
      var content = document.getElementById("CONTENT")
      var y = findXY(content).y + (content.offsetHeight)*p/100;
      window.scrollTo(0, y-16);
    }
  }

  var adr = document.location.hash.match(/selection-(\d+)\.(\d+)-(\d+)\.(\d+)/);
  if (adr) {
    var pos=0,begin=null,end=null;
    function recur(e) {
      if (e.nodeType==1) pos = (pos&~1)+2;
      if (e.nodeType==3) pos = pos|1;
      if (pos==adr[1]) begin=[e, adr[2]];
      if (pos==adr[3]) end  =[e, adr[4]];
      for (var i=0; i<e.childNodes.length; i++)
        recur(e.childNodes[i]);
      if (e.childNodes.length>0 && e.lastChild.nodeType==3)
        pos = (pos&~1)+2;
    }
    var content = document.getElementById("CONTENT");
    recur(content.childNodes[content.childNodes[0].nodeType==3 ? 1 : 0]);
    if (begin!=null && end!=null) {
      window.scrollTo(0, findXY2(begin[0], begin[1]).y-8);

      if (window.getSelection) {
        var sel = window.getSelection();
        sel.removeAllRanges();
        var range = document.createRange();
        range.setStart(begin[0], begin[1]);
        range.setEnd  (  end[0],   end[1]);
        sel.addRange(range);
      } else if (document.selection) { // IE
      }
    }
  }
}
window.onhashchange = scrollToHash;
var initScrollToHashDone = false;
function initScrollToHash() {
  if (!initScrollToHashDone) {
    initScrollToHashDone = true;
    scrollToHash();
  }
}
window.onload = initScrollToHash;
setTimeout(initScrollToHash, 500); /* onload can be delayed by counter code */
```
</details>

**Comment by Raytle** [comment]
"The perfect is the enemy of the good."

Why not implement the following solution which, I suppose, would be "pretty good" although certainly imperfect.

1. Using ArchiveBox he user selects a block of text on the page which he would like to his browser to automatically "jump to" in the future. 
2. ArchiveBox will open that page, and then
3. ArchiveBox will open the `Find...`
4. ArchiveBox will **paste** the aforementioned block of text.
5. ArchiveBox will **search** the aforementioned block of text.

Obviously if a the block of text existed more than once on a page the feature might incorrectly find a "wrong" block of text. Users, therefore, should choose sufficiently long blocks of text to minimize the risk of that problem and, furthermore, be prepared for ArchiveBox to sometimes find a "wrong" block of text.

Mobile phones, GPS, and, well, virtually every technology has limitations (imperfections). When working with technological limitations, the proper question to ask generally isn't, "What's possible?" but rather, "What is feasible?"

**Comment by infogulch** [comment]
Is it feasible for a web page to control the browser's `Find on page` feature? I do not know if that is possible; I've never seen it before, as a specific instance or in the js api.

**Comment by Raytle** [comment]
> OH I just noticed your suggestion is not an implementation strategy, but more "stop being so lazy and just use the Find on page feature your damn self" haha (though you said it a bit nicer).

You misconstrued my meaning. I wasn't being diplomatic; rather, I was being forthright.

I'm not a tech guy but I use the popular [PyAutoGui](https://github.com/asweigart/pyautogui) frequently so that I can automate stuff without bothering to learn the "proper way" to write Python scripts. I have actually learned to write some code in Python. But really, for a non-engineer (a "normie" or a "normal person") why should any of learn more than just a little Python?

I don't know much about Python and I know almost nothing about Javascript. I incorrectly assumed Javascript had something like PyAutoGui built-in, but I suppose perhaps it does not.


> Is it feasible for a web page to control the browser's Find on page feature?

Based on my cursory research it seems like it is probably **not** feasible.

Please see...

1. [Can I programmatically open the browser's native search dialogue by JavaScript?](https://stackoverflow.com/questions/52835530/can-i-programmatically-open-the-browsers-native-search-dialogue-by-javascript), and
2. [How to trigger browser's find (ctrl+F) on button click.](https://stackoverflow.com/questions/44989903/how-to-trigger-browsers-find-ctrlf-on-button-click)


> A link directly to a particular paragraph is 10x more valuable than a link to the top of a long page

I agree wholeheartedly with that sentiment. I think your feature request should be a high priority item. 

Devs almost always conflate features with benefits. That is to say, devs often spend countless hours working on features that precious few users ever end up using, yet often ignore technically trivial features that would the overwhelming majority of their users would be very glad to use.

Based on my research it would be trivial to have Javascript find text on a page as is discussed within the aforementioned link which I have copied and pasted to here [The first answer to, "Can I programmatically open the browser's native search dialogue by JavaScript?"](https://stackoverflow.com/a/68483029/15661404).

I suppose that either the user would need to merely **highlight** the text he wanted ArchiveBox to find on a particular page or, perhaps, the user would need to actually **copy** the text he wanted ArchiveBox to find on a particular page.

Then I suppose ArchiveBox would perhaps only find the first instance of that text. In such a case, users of that feature would probably quickly learn to select larger blocks of text rather than smaller blocks of text to ensure that the first instance of that block of text found was normally the sole instance of that block of text. Furthermore, in such a case then I suppose that I would probably normally triple click in the middle of a paragraph so as to select the entire paragraph thereby normally ensuring I had chosen a unique block of text.

**Basically my point is this**: it seems likely that a competent intermediate level JavaScript programmer could implement a "pretty good" yet not "perfect" version of feature you (and I) both want.

What ends up happening 90% of the time in FOSS/FLOSS projects is this: because there's no product manager to force the devs (or often simply, the dev) to implement a feature users want, the dev(s) ignore the feature because it doesn't [scratch an itch](https://en.wiktionary.org/wiki/scratch_an_itch#:~:text=(idiomatic)%20To%20satisfy%20a%20need%20or%20desire.) of theirs.

I invariably run into this problem when I work with various freelance programmers and freelance artists. As long as I am the client (who is paying them) I often end up reluctantly forcing them to implement features which I believe my customers and/or potential customers would like to have. In other words, programmers and artists (both groups which I consider to be idealistic/dreamers) are often so different from normal people, who often have a mundane yet important need that is not being addressed, that I must act—often forcefully and unpleasantly—as a "customer advocate." 

Put simply: I often issue an order, "You must add this feature for my customers and/or potential customers or else I intend to terminate our relationship." It gets ugly often particularly with the programmers (who typically think features like the one in this issue are stupid or at least unnecessary). I don't enjoy my role as stern taskmaster... at all. But it's part of my job. Project managers/clients are often unpopular with those whom they manage.
