### ISSUE TITLE
ArchiveBox should never be run as root Windows Docker create super user

### ISSUE THREAD

**Issue by cybrpimp** [ArchiveBox/ArchiveBox#838]
I've was able to install ArchiveBox on Docker without a problem from the Docker Hub download, but when I try to create a superuser I get the following error;

![image](https://user-images.githubusercontent.com/61793417/131432557-77acf203-2cf5-46c9-b797-7598ae3b1811.png)

![image](https://user-images.githubusercontent.com/61793417/131432668-bed248cf-c220-4504-820b-22f0e73003d3.png)

**Comment by likuilin** [comment]
I got the same issue. As a workaround, you can `su archivebox` first and then do whatever you need to do, or you can specify the username to use to docker by doing `docker-compose exec -u archivebox archivebox archivebox create superuser`

**Comment by pirate** [comment]
You should use `run` not `exec`, it will handle the user permissions correctly for you:

    docker-compose run archivebox manage createsuperuser

**Comment by likuilin** [comment]
Good point! Though if you do that, you're spinning up a separate docker container, so you should add `--rm` or else you leave behind a stopped container that isn't cleaned up.

**Comment by pirate** [comment]
In my experience they don't take up appreciable additional disk space because of docker's BTFS COW-based filesystem. If you want to clean them up you can always run `docker system prune`. You're welcome to add `--rm`, but I don't add it to the examples/docs in order to keep them as short, simple, and intuitive as possible.
