### ISSUE TITLE
Bug: Empty image spaces where images are supposed to be

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ArchiveBox/ArchiveBox#883]
#### Describe the bug
Empty Image Spaces, where Images are supposed to be. Singlefile, Wget both show empty images. 

#### Steps to reproduce
Go to https://mariushosting.com/ and archive any of the posts

#### Screenshots or log output
https://ibb.co/QJHGWzC

#### ArchiveBox version
latest

**Comment by Unrepentant-Atheist** [comment]
I went to the wiki, and found this: https://github.com/gildas-lormeau/SingleFile/ , I tried this on all the archived URLs that had missing images, and every single file made with https://github.com/gildas-lormeau/SingleFile/ worked and had all the images. Maybe implement this into ArchiveBox!

**Comment by iwconfig** [comment]
Isn't `SingleFile` already implemented?

**Comment by pirate** [comment]
ArchiveBox Singlefile is gildas-lormeau/SingleFile.

**Comment by pirate** [comment]
Could be because we aren't using the latest version, SingleFile is adding new features all the time and we're a bit behind. The next ArchiveBox release will bump it to the latest version + latest Chrome version.

**Comment by GlassedSilver** [comment]
> Could be because we aren't using the latest version, SingleFile is adding new features all the time and we're a bit behind. The next ArchiveBox release will bump it to the latest version + latest Chrome version.

Would it be feasible to update SingleFile from the source periodically automatically?

Same for ytdl/yt-dlp.

The releases taking their time is okay, but I'd be good to have instances pull independently of releases the tools needed.

The web is progressing faster and faster and to keep up with dependencies of these sorts is crucial in getting consistently good mirrors.

Since I run archivebox in a docker image it'd be really cool if this functionality could be baked in. :)

Another site to test this with: https://xemu.app/

**Comment by melyux** [comment]
Please bump Singlefile, the current version is _ancient_

**Comment by pirate** [comment]
Singlefile should already be bumped in the latest dev branch, please try that version: https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch

**Comment by pirate** [comment]
Singlefile and Chrome are both on the most recent versions in [ArchiveBox 0.7.1](https://github.com/ArchiveBox/ArchiveBox/releases), so this should be resolved. Please comment back here if you're still having issues and I'll re-open the ticket.
