### ISSUE TITLE
Clarify admin UI button behavior + document the details of how they behave

### ISSUE THREAD

**Issue by meonkeys** [ArchiveBox/ArchiveBox#930]
Hi there! Just had a few questions.

1. What does "title" do in the web UI? It appears to re-try fetching headers, favicon, and HTML title for content at a URL -- is that correct?
2. What does "pull" do in the web UI?
3. How about if we added tooltips (HTML `title` attributes) to the "title", "pull", "re-snapshot", "reset", and "delete" buttons to `/admin/core/snapshot/` in the web UI? I couldn't find an existing issue for this. I'm happy to file one and help out.
4. Say I used re-snapshot a bunch of days in a row. Is there some easy way to see/list all the versions I've snapshotted for a particular URL? When I click "History" on the admin page for a snapshot, it says "This object doesn’t have a change history. It probably wasn’t added via this admin site.". I saw #179 so I'm guessing this isn't implemented yet.
5. Sometimes when I visit the index page for a snapshot, my browser (Firefox) starts automatically downloading an `output.pdf` file. Why? [example archivebox snapshot index page showing this behavior](https://arc.bitma.st/archive/1645513427.445168/index.html)
6. ~~Is there any way to strip ads and trackers?~~ found #211 , awesome!

Thank you, -Adam

**Comment by akhilleusuggo** [comment]
> How about if we added tooltips (HTML title attributes) to the "title", "pull", "re-snapshot", "reset", and "delete" buttons to /admin/core/snapshot/ in the web UI? I couldn't find an existing issue for this. I'm happy to file one and help out.

-Title : Pull the title ( redownload if it was missing, or the title has changed )

-Pull: Download missing/failed outputs/extractors methods ( pdf, wget... etc). Maybe because download failed or interrupted by a reboot or something. This is the default behavior when you add new URL, they will get pulled automatically. https://github.com/ArchiveBox/ArchiveBox#output-formats

-Re-snapshot: As the name suggests, re-download the page as a separated unique page. Not the same as pull, this one will create a separate entry, and the page is treated as a new URL ending with the date and time `#2020-10-24-08:00` https://github.com/ArchiveBox/ArchiveBox#saving-multiple-snapshots-of-a-single-url

-Reset: Delete all type of output and redownload them. In the contrary of snapshot, this will **_overwrite_** the files.

**Comment by meonkeys** [comment]
I added your documentation to https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#explanation-of-buttons-in-the-web-ui---admin-snapshots-list ! I hope this is OK.

**Comment by meonkeys** [comment]
Any thoughts on 5 above (`output.pdf`)?

**Comment by akhilleusuggo** [comment]
Maybe you browser doesn't support PDF and needs to download it since it can't open it. ( I don't think is the reason but it could be )

But I don't understand what do you mean by 

> Sometimes when I visit the index page for a snapshot

If you browser does support PDF reading then should not be any problem. Tweak this settings. Must be set to open in firefox

![image](https://user-images.githubusercontent.com/52116577/155701627-20723317-4f43-4741-9e9f-2cfd637b31c6.png)

**Comment by meonkeys** [comment]
Oh dangit, you're right!

For posterity: it looks like Firefox must indeed be configured to open PDFs in Firefox (as opposed to the other options: Always ask, Save File, etc) for this to work properly. On a snapshot index page, the PDF viewer tries to open the PDF in an iframe. If Firefox is set to Save File, the iframe instead ends up triggering a file download of `output.pdf`.

**Comment by pirate** [comment]
Considering re-naming these buttons for clarity + updating the tooltip help text that appears on hover:

- `⬇️ Title` -> `Get title` (Make an initial request to fetch the page's title, headers, and response code)
- `Pull` -> `Resume` (Resume archiving a snapshot that was interrupted during archiving / retry any methods that failed to produce output on the first try)
- `Re-Snapshot` -> `Re-Snapshot URL` (Create a new separate snapshot of this URL and archive it from scratch as it appears right now)
- `Reset` -> `-` just going to remove this button I think, I don't think it's that useful and you can accomplish it with Re-Snapshot + Delete on the original
- `Delete` -> stays the same

Open to suggestions. The difficulty is that I have to keep these really short to fit them in the UI nicely (especially for smaller screen sizes), otherwise it would be easy to give them long descriptive names.

**Comment by meonkeys** [comment]
What if you we left <kbd>⬇️ Title</kbd> as-is, but added a long tooltip? We could use long, descriptive text in the tooltip: exactly what you wrote in parens. So <kbd>⬇️ Title</kbd> stays the same, but when you hover over it you see `Make an initial request to fetch the page's title, headers, and response code`.

Renaming <kbd>Pull</kbd> to <kbd>Resume</kbd> sounds great, as does getting rid of <kbd>Reset</kbd>.

<kbd>Resume</kbd> tooltip: `Resume archiving a snapshot that was interrupted during archiving / retry any methods that failed to produce output on the first try`.

<kbd>Re-Snapshot</kbd> seems fine as-is, especially if it gets the tooltip `Create a new separate snapshot of this URL and archive it from scratch as it appears right now`.

<kbd>Delete</kbd> seems clear as-is, without a tooltip.

**Comment by huyz** [comment]
I've also been confused by the current terminology, which always made me think too hard.

So to experiment, I created a user script (for Violentmonkey or Tampermonkey) with new terminology.

If you might want to try it out
```js
// ==UserScript==
// @name        ArchiveBox: rename action buttons
// @namespace   Violentmonkey Scripts
// @match       *://archivebox.mydomain/*
// @grant       none
// @version     1.0
// @author      -
// @description 8/2/2024, 9:05:21 AM
// ==/UserScript==

window.addEventListener('load', function() {
  if (!$) {
    return;
  }

  $('button[name="update_titles"]').text('⬇️ Get Title').attr('title', 'Fetch only the title and favicon.');
  $('button[name="update_snapshots"]').text('⏯️ Get Missing').attr('title', 'Finish the Snapshot, fetching any missing or failed outputs formats');
  const $replicate = $('button[name="resnapshot_snapshot"]').text('🆕 Replicate').attr('title', 'Create and fetch a new separate snapshot with the same URL');
  $('button[name="overwrite_snapshots"]').text('🔁 Redo').attr('title', 'Overwrite the existing snapshot files and re-fetch').insertBefore($replicate);
  $('button[name="delete_snapshots"]').text('💀 Delete').attr('title', 'Delete the snapshot and its files');

  // Simplify page title
  const $document = $(document);
  const title = $document.attr('title');
  if (title === 'Select snapshot to change | Index | ArchiveBox') {
    $document.attr('title', 'ArchiveBox');
  } else if (title === 'Select Tag to change | Index | ArchiveBox') {
    $document.attr('title', 'ArchiveBox tags');
  } else if (title === 'Select archive result to change | Index | ArchiveBox') {
    $document.attr('title', 'ArchiveBox log');
  } else if (title === 'Archived Sites') {
    $document.attr('title', 'ArchiveBox - public');
  }
});
```

Please don't get rid of `Reset` (which I call `Redo`) as it's my most commonly-used button.

**Comment by pirate** [comment]
Thanks for contributing! I've never liked the names I came up with for these buttons and yours are way better. I'll incorporate these into the next release 👌😊

**Comment by pirate** [comment]
This is done in v0.8.3-rc! https://github.com/ArchiveBox/ArchiveBox/releases/tag/v0.8.3-rc

![Screenshot 2024-09-06 at 3 22 01 AM Get Title Get Missing Archive again](https://github.com/user-attachments/assets/bbe08dec-1440-4dae-b7de-d0ffdf6040a8)
