### ISSUE TITLE
Question: When is there going to be a new release?

### ISSUE THREAD

**Issue by Victor239** [ArchiveBox/ArchiveBox#983]
It's been over a year since the last one, it would be good to have a new one to take advantage of the changes that have occurred in the past year without having to build the app individually.

**Comment by pirate** [comment]
v0.6.3 is up on Docker Hub already but I haven't rolled the release for pip/apt/brew/etc. because there are still some final bugs to work out. Should be in the next month or two, but if you want it early you can run from Docker or follow these instructions: https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch

**Comment by karlicoss** [comment]
I was on latest docker, but apparently using the old container name, `nikisweeting/archivebox:latest` hasn't been updated lately. 
I'm gonna switch to `archivebox/archivebox`, but not sure if the former repo should be updated too since it's meant to be a legacy mirror? Thanks!

https://hub.docker.com/r/nikisweeting/archivebox/tags?page=1&name=latest
https://hub.docker.com/r/archivebox/archivebox/tags?page=1&name=latest

**Comment by pirate** [comment]
The former repo is automatically updated but only on official releases. `archivebox/archivebox:latest` is actually a pre-release beta right now because I needed to fix some urgent UX breaking bugs and a full release takes a lot more effort.
